type: fields
fields:
  cover: @hksagentur/schema/fields/cover
  created: @hksagentur/schema/fields/created
  updated: @hksagentur/schema/fields/updated
  author: @hksagentur/schema/fields/author
  tags: @hksagentur/schema/fields/tags