type: files
label:
  *: hksagentur.schema.field.gallery.label
query: page.images.template('image')
layout: cardlets
multiple: true
info: "{{ file.dimensions }} ({{ file.niceSize }})"
uploads:
  template: image