type: writer
label:
  *: hksagentur.schema.field.heading.label
placeholder:
  *: hksagentur.schema.field.heading.placeholder
inline: true
nodes: false
marks:
  - bold
  - italic
  - underline
  - strike
  - code