type: group
fields:
  extends: @hksagentur/schema/fields/name
  description:
    extends: @hksagentur/schema/fields/inline-text
    label:
      *: hksagentur.schema.field.person.description
  lineContact:
    type: line
  telephone: @hksagentur/schema/fields/telephone
  fax: @hksagentur/schema/fields/fax
  email: @hksagentur/schema/fields/email
  lineTaxonomies:
    type: line
  occupation: @hksagentur/schema/fields/occupation
  responsibilities: @hksagentur/schema/fields/responsibilities