title:
  *: hksagentur.schema.file.document.title

icon: document

accept:
  type:
    - document
    - archive

image:
  query: model.cover.toFile
  ratio: 3/2
  cover: false

columns:
  main:
    width: 2/3
    fields:
      label:
        extends: @hksagentur/schema/fields/heading
        label:
          *: hksagentur.schema.file.document.label
      description:
        extends: @hksagentur/schema/fields/inline-text
        label:
          *: hksagentur.schema.file.document.description
  sidebar:
    width: 1/3
    fields:
      cover:
        extends: @hksagentur/schema/fields/image
        label:
          *: hksagentur.schema.file.document.cover
      author:
        type: text
        label:
          *: hksagentur.schema.file.document.author
        icon: user
        counter: false
      source:  @hksagentur/schema/fields/source
