title:
  *: hksagentur.schema.file.document.title

icon: document

accept:
  type:
    - document
    - archive

image:
  query: model.cover.toFile
  ratio: 3/2
  cover: false

columns:
  main:
    width: 2/3
    fields:
      description:
        type: textarea
        label:
          *: hksagentur.schema.file.document.description
        size: medium
        buttons:
          - italic
          - bold
          - link
          - email
  sidebar:
    width: 1/3
    fields:
      cover:
        extends: @hksagentur/schema/fields/image
        label:
          *: hksagentur.schema.file.document.cover
      author:
        type: text
        label:
          *: hksagentur.schema.file.document.author
        icon: user
        counter: false
      source: fields/source
