<?php

return [
    '@hksagentur/schema/files/document' => __DIR__ . '/blueprints/files/document.yml',
    '@hksagentur/schema/files/image' => __DIR__ . '/blueprints/files/image.yml',
    '@hksagentur/schema/files/logo' => __DIR__ . '/blueprints/files/logo.yml',
    '@hksagentur/schema/files/video' => __DIR__ . '/blueprints/files/video.yml',
    '@hksagentur/schema/fields/address' => __DIR__ . '/blueprints/fields/address.yml',
    '@hksagentur/schema/fields/author' => __DIR__ . '/blueprints/fields/author.yml',
    '@hksagentur/schema/fields/channels' => __DIR__ . '/blueprints/fields/channels.yml',
    '@hksagentur/schema/fields/coordinates' => __DIR__ . '/blueprints/fields/coordinates.yml',
    '@hksagentur/schema/fields/cover' => __DIR__ . '/blueprints/fields/cover.yml',
    '@hksagentur/schema/fields/created' => __DIR__ . '/blueprints/fields/created.yml',
    '@hksagentur/schema/fields/currency' => __DIR__ . '/blueprints/fields/currency.yml',
    '@hksagentur/schema/fields/email' => __DIR__ . '/blueprints/fields/email.yml',
    '@hksagentur/schema/fields/gallery' => __DIR__ . '/blueprints/fields/gallery.yml',
    '@hksagentur/schema/fields/fax' => __DIR__ . '/blueprints/fields/fax.yml',
    '@hksagentur/schema/fields/hours' => __DIR__ . '/blueprints/fields/hours.yml',
    '@hksagentur/schema/fields/hours-exception' => __DIR__ . '/blueprints/fields/hours-exception.yml',
    '@hksagentur/schema/fields/hours-day' => __DIR__ . '/blueprints/fields/hours-day.yml',
    '@hksagentur/schema/fields/image' => __DIR__ . '/blueprints/fields/image.yml',
    '@hksagentur/schema/fields/license' => __DIR__ . '/blueprints/fields/license.yml',
    '@hksagentur/schema/fields/link' => __DIR__ . '/blueprints/fields/link.yml',
    '@hksagentur/schema/fields/logo' => __DIR__ . '/blueprints/fields/logo.yml',
    '@hksagentur/schema/fields/name' => __DIR__ . '/blueprints/fields/name.yml',
    '@hksagentur/schema/fields/navigation' => __DIR__ . '/blueprints/fields/navigation.yml',
    '@hksagentur/schema/fields/occupation' => __DIR__ . '/blueprints/fields/occupation.yml',
    '@hksagentur/schema/fields/organization' => __DIR__ . '/blueprints/fields/organization.yml',
    '@hksagentur/schema/fields/person' => __DIR__ . '/blueprints/fields/person.yml',
    '@hksagentur/schema/fields/price' => __DIR__ . '/blueprints/fields/price.yml',
    '@hksagentur/schema/fields/published' => __DIR__ . '/blueprints/fields/published.yml',
    '@hksagentur/schema/fields/responsibilities' => __DIR__ . '/blueprints/fields/responsibilities.yml',
    '@hksagentur/schema/fields/source' => __DIR__ . '/blueprints/fields/source.yml',
    '@hksagentur/schema/fields/tags' => __DIR__ . '/blueprints/fields/tags.yml',
    '@hksagentur/schema/fields/telephone' => __DIR__ . '/blueprints/fields/telephone.yml',
    '@hksagentur/schema/fields/updated' => __DIR__ . '/blueprints/fields/updated.yml',
    '@hksagentur/schema/fields/video' => __DIR__ . '/blueprints/fields/video.yml',
    '@hksagentur/schema/fields/website' => __DIR__ . '/blueprints/fields/website.yml',
    '@hksagentur/schema/sections/meta' => __DIR__ . '/blueprints/sections/meta.yml',
];
