<?php

use Kirby\Toolkit\A;
use Kirby\Cms\App;
use Kirby\Data\Yaml;

return A::reduce([
    'blocks/accordion-item',
    'blocks/accordion',
    'blocks/billboard',
    'blocks/card',
    'blocks/cards',
    'blocks/collection',
    'blocks/disclosure',
    'blocks/gallery',
    'blocks/heading',
    'blocks/hero',
    'blocks/image',
    'blocks/media-text',
    'blocks/tabs',
    'blocks/video',
    'fields/actions',
    'fields/address',
    'fields/align-content',
    'fields/author',
    'fields/blocks',
    'fields/caption',
    'fields/category',
    'fields/channels',
    'fields/content-layout',
    'fields/coordinates',
    'fields/cover',
    'fields/created',
    'fields/currency',
    'fields/email',
    'fields/eyebrow',
    'fields/fax',
    'fields/featured',
    'fields/flip',
    'fields/gallery',
    'fields/heading-level',
    'fields/heading',
    'fields/hours-day',
    'fields/hours-exception',
    'fields/hours',
    'fields/image',
    'fields/inline-text',
    'fields/justify-content',
    'fields/license',
    'fields/limit',
    'fields/link',
    'fields/logo',
    'fields/markdown',
    'fields/name',
    'fields/navigation',
    'fields/occupation',
    'fields/offset',
    'fields/open',
    'fields/organization',
    'fields/person',
    'fields/price',
    'fields/published',
    'fields/ratio',
    'fields/responsibilities',
    'fields/rich-text',
    'fields/source',
    'fields/tags',
    'fields/telephone',
    'fields/updated',
    'fields/video',
    'fields/website',
    'files/document',
    'files/image',
    'files/logo',
    'files/video',
    'pages/article',
    'pages/default',
    'pages/employee',
    'sections/documents',
    'sections/images',
    'sections/meta',
    'sections/pages',
    'sections/subpages',
    'sections/taxonomies',
    'sections/videos',
    'tabs/content',
    'tabs/media',
    'tabs/settings',
], static function (array $blueprints, string $name): array {
    return $blueprints + [
        "@hksagentur/schema/{$name}" => fn (App $kirby): array => $kirby->apply(
            name: 'hksagentur.schema.blueprint:after',
            args: [
                'name' => $name,
                'blueprint' => Yaml::read(__DIR__ . '/blueprints/' . $name . '.yml'),
            ],
            modify: 'blueprint',
        ),
    ];
}, []);
